### ISSUE TITLE
New installs on Windows - iblviewer fails to launch - no error

### ISSUE THREAD

**Issue by oliche** [int-brain-lab/iblviewer#13]
When installing on Windows using a fresh conda environment, the viewer fails to launch.

We tried:

- command line `iblviewer`: the windows shows up, black, then freezes and disappear
- Python prompt launch: same as launcher
- IPython prompt launch: the windows freezes and the prompt has to be killed. (Window not responding)

This is reproducible on at least 3 computers so far.

**Comment by nantille** [comment]
It would have been worth trying `iblviewer -ui 0` as a test. The viewer does work but not the matplotlib in the QT UI (which is the default option when starting iblviewer). I have disabled this feature on Windows for the time being. This only affects having custom statistics in the QT UI.

Since the default UI for Python and iPython prompt is QT, the problem was the same. This is now fixed.

You may `pip install -U iblviewer`.

**Comment by nantille** [comment]
Closing this. Feel free to comment or reopen if necessary.
