### ISSUE TITLE
Feature request: make a movie

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblviewer#3]
Everybody loves 3D rotating brains so it would be nice if the viewer has a button you can press which rotates the brain you're looking at 360 degrees and outputs a video of that in mp4 format.

**Comment by nantille** [comment]
A first integration of this feature is available. Since now the integration with Jupyter lab and notebooks works as intended. The duration and amount of rotation is easily customizable. I'll add an example notebook as a demo. Otherwise the default duration for the button "Export turntable movie" is set to 8 seconds at 25fps for a 360° on dorso-ventral axis.
You can try this with `pip install git+https://github.com/int-brain-lab/iblviewer.git`

**Comment by guidomeijer** [comment]
Amazing, this is great! Small suggestion: the option to not show the colorbar in the video.

**Comment by nantille** [comment]
@guidomeijer The tool has now been upgraded to version 2 with many changes and new features. There are now integrated options in the UI for the video export. And more options can be easily added.
