### ISSUE TITLE
Error while loading example data in ibl_point_neurons

### ISSUE THREAD

**Issue by guidomeijer** [int-brain-lab/iblviewer#6]
When running `ibl_point_neurons.py` I'm getting the following error:

```
Traceback (most recent call last):

  File "C:\Users\guido\Repositories\int-brain-lab\iblviewer\examples\neuroscience\ibl_point_neurons.py", line 79, in <module>
    positions, timings, min_v, max_v = process_point_neurons(data_set)

  File "C:\Users\guido\Repositories\int-brain-lab\iblviewer\examples\neuroscience\ibl_point_neurons.py", line 31, in process_point_neurons
    with (open(os.path.abspath(data_path), 'rb')) as openfile:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\guido\\anaconda3\\envs\\iblenv\\lib\\site-packages\\examples\\data\\exp2_db4df448-e449-4a6f-a0e7-288711e7a75a_both'
```

I believe this is because the EXAMPLE_DATA_FOLDER in `utils` is somehow missing `iblviewer` in it.

**Comment by nantille** [comment]
You are right and this was fixed with the lastest update. Please update the viewer. You will be able to run all examples in the terminal with shortcuts. Start the viewer with `iblviewer`. If you hit tab twice before you hit enter, you will see other propositions for demos, like `iblviewer-points-demo`. Lots of features were added and stabilized in the new update, including a Qt UI. You can also run the viewer headless on a supercomputer if you wish.
